Pr3Obligatorio_AAN2023/Controllers/AdministrativoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Pr3Obligatorio_AAN2023.Datos;
using Pr3Obligatorio_AAN2023.Models;

namespace Pr3Obligatorio_AAN2023.Controllers
{
    public class AdministrativoesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdministrativoesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Administrativoes
        public async Task<IActionResult> Index()
        {
              return _context.Administrativos != null ? 
                          View(await _context.Administrativos.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Administrativos'  is null.");
        }

        // GET: Administrativoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Administrativos == null)
            {
                return NotFound();
            }

            var administrativo = await _context.Administrativos
                .FirstOrDefaultAsync(m => m.NumeroTrabajador == id);
            if (administrativo == null)
            {
                return NotFound();
            }

            return View(administrativo);
        }

        // GET: Administrativoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Administrativoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NumeroTrabajador,Nombre,Apellido,Telefono,Email,Constraseña")] Administrativo administrativo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(administrativo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(administrativo);
        }

        // GET: Administrativoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Administrativos == null)
            {
                return NotFound();
            }

            var administrativo = await _context.Administrativos.FindAsync(id);
            if (administrativo == null)
            {
                return NotFound();
            }
            return View(administrativo);
        }

        // POST: Administrativoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NumeroTrabajador,Nombre,Apellido,Telefono,Email,Constraseña")] Administrativo administrativo)
        {
            if (id != administrativo.NumeroTrabajador)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(administrativo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdministrativoExists(administrativo.NumeroTrabajador))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(administrativo);
        }

        // GET: Administrativoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Administrativos == null)
            {
                return NotFound();
            }

            var administrativo = await _context.Administrativos
                .FirstOrDefaultAsync(m => m.NumeroTrabajador == id);
            if (administrativo == null)
            {
                return NotFound();
            }

            return View(administrativo);
        }

        // POST: Administrativoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Administrativos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Administrativos'  is null.");
            }
            var administrativo = await _context.Administrativos.FindAsync(id);
            if (administrativo != null)
            {
                _context.Administrativos.Remove(administrativo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdministrativoExists(int id)
        {
          return (_context.Administrativos?.Any(e => e.NumeroTrabajador == id)).GetValueOrDefault();
        }
    }
}

Pr3Obligatorio_AAN2023/Controllers/InicioAdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Pr3Obligatorio_AAN2023.Datos;
using Pr3Obligatorio_AAN2023.Models;

namespace Pr3Obligatorio_AAN2023.Controllers
{
    public class InicioAdminController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly IMemoryCache _cache;

        public InicioAdminController(ApplicationDbContext context, IMemoryCache cache)
        {
            _context = context;
            _cache = cache;
        }
        public ActionResult InicioAdmin()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(Administrativo u)
        {
            {
                if (u != null)
                {
                    // Verificar si el correo pertenece a un administrador
                    var Administrativo = _context.Administrativos.FirstOrDefault(obj => obj.Email == u.Email);
                    if (Administrativo != null)
                    {
                        // Verificar que el correo termine con "@admin.com"
                        if (!u.Email.EndsWith("@admin.com"))
                        {
                            TempData["mensajeError"] = "No eres admin";
                            return RedirectToAction("InicioAdmin");
                        }

                        if (u.Constraseña != Administrativo.Constraseña)
                        {
                            TempData["mensajeError"] = "La contraseña es incorrecta!";
                        }
                        else
                        {
                            _cache.Set("Administrativo", Administrativo);
                            return RedirectToAction("Index", "Home");
                        }
                    }
                    else
                    {
                        TempData["mensajeError"] = "No eres admin";
                    }
                }
                else
                {
                    TempData["mensajeError"] = "Ingrese correo y contrase単a";
                }

                return RedirectToAction("InicioAdmin");
            }
        }
    }
}

Pr3Obligatorio_AAN2023/Views/InicioAdmin/InicioAdmin.cshtml
@model Administrativo

@{
    var mensajeError = TempData["mensajeError"] as string;
}

@if (!string.IsNullOrEmpty(mensajeError))
{
    <div class="alert alert-danger">
        @mensajeError
    </div>
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login más lindo</title>
    <!-- CSS de Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Estilos adicionales -->
    <link href="~/css/styles.css" rel="stylesheet" />

    <style>
        body {
            background: #3C4048;
            background: linear-gradient(to left, #3C4048, #3C40);
        }

        .card-img-left {
            width: 45%;
            /* Link to your background image using in the property below! */
            background: scroll center url('https://img.freepik.com/foto-gratis/grupo-gente-joven-cine_23-2148115362.jpg?w=360&t=st=1690158835~exp=1690159435~hmac=405a08b86ec6772906db33bc47ab17cc64572fb7209dce71422486e459507ed1');
            background-size: cover;
        }

        .btn-login {
            font-size: 0.9rem;
            letter-spacing: 0.05rem;
            padding: 0.75rem 1rem;
        }

        .btn-google {
            color: white !important;
            background-color: #ea4335;
        }

        .btn-facebook {
            color: white !important;
            background-color: #3b5998;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-9 mx-auto">
                <div class="card flex-row my-5 border-0 shadow rounded-3 overflow-hidden">
                    <div class="card-img-left d-none d-md-flex">
                        <!-- Background image for card set in CSS! -->
                    </div>
                    <div class="card-body p-4 p-sm-5">
                        <h5 class="card-title text-center mb-5 fw-light fs-5">Iniciar Sesion</h5>
                        <h5 class="card-title text-center  fw-light fs-5">Administrador</h5>
                        <form method="post" asp-action="Login" asp-controller="InicioAdmin">


                            <div class="form-floating mb-3">
                                <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Ingrese su email" required asp-for="Email">
                                <label for="exampleInputEmail1">Email</label>
                            </div>
                            <hr>
                            <div class="form-floating mb-3">
                                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Ingrese su contraseña" required asp-for="Constraseña">
                                <label for="exampleInputPassword1">Password</label>
                            </div>
                            <div class="d-grid mb-2">
                                <button class="btn btn-lg btn-primary  btn-login fw-bold text-uppercase" type="submit">Iniciar Sesion</button>
                                <label class="alert-danger">@ViewBag.Error</label>

                            </div>
                            <a class="d-block text-center mt-2 small" asp-controller="Administrativoes" asp-action="Create">No tienes cuenta? Registrate</a>

                            <hr class="my-4">

                            <div class="d-grid mb-2">
                                <button class="btn btn-lg btn-google btn-login fw-bold text-uppercase" type="submit">
                                    <i class="fab fa-google me-2"></i> Iniciar con Google
                                </button>
                            </div>

                            <div class="d-grid">
                                <button class="btn btn-lg btn-facebook btn-login fw-bold text-uppercase" type="submit">
                                    <i class="fab fa-facebook-f me-2"></i> Iniciar con Facebook
                                </button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    s
    <!-- JavaScript de Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>